import { TextModel } from "@/types/chatgpt";

export const textModels: TextModel[] = [
  {
    model: "gpt-4o",
    name: "ChatGPT 4o",
    description: "برای اکثر سوالات عالی است",
    canReasoning: false,
    canWebSearch: true,
    canFileSearch: false,
    input_price_per_million_tokens: 2.5,
    output_price_per_million_tokens: 10,
  },
  // {
  //   model: 'o3',
  //   name: 'ChatGPT o3',
  //   description: 'قوی ترین در استدلال پیشرفته',
  //   canReasoning: true,
  //   canWebSearch: false,
  //   canFileSearch: false,
  //   canGenerateImage: false,
  //   input_price_per_million_tokens: 10,
  //   output_price_per_million_tokens: 40,
  // },
  {
    model: "o4-mini",
    name: "ChatGPT o4 mini",
    description: "سریع‌ترین در استدلال پیشرفته",
    canReasoning: true,
    canWebSearch: false,
    canFileSearch: false,
    input_price_per_million_tokens: 1.1,
    output_price_per_million_tokens: 4.4,
  },
  {
    model: "gpt-4o-mini",
    name: "ChatGPT 4o mini",
    description: "عالی برای کارهای روزمره",
    canReasoning: false,
    canWebSearch: true,
    canFileSearch: false,
    input_price_per_million_tokens: 0.15,
    output_price_per_million_tokens: 0.6,
  },
];
